on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: krispil.azurecr.io
        username: ${{ secrets.acr_krispil_username }}
        password: ${{ secrets.acr_krispil_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t krispil.azurecr.io/krispil:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push krispil.azurecr.io/krispil:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_krispil_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep krispil9a61 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace krispil9a61`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: krispil9a61
        container-registry-url: krispil.azurecr.io
        container-registry-username: ${{ secrets.acr_krispil_username }}
        container-registry-password: ${{ secrets.acr_krispil_password }}
        secret-name: krispildockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: krispil9a61
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          krispil.azurecr.io/krispil:${{ github.sha }}
        imagepullsecrets: |
          krispildockerauth
